### ISSUE TITLE
Доработать юзерстори и юзкейсы

### ISSUE THREAD

**Issue by IvanYarlichenco** [IvanYarlichenco/gameIgra#12]
https://docs.google.com/document/d/1bhX_ETuCbR9ZSjh7ArzO3JGF502FLhXTEivb4HIPN1w/edit

**Comment by Timanchik** [comment]
[Usecase & UserStory .docx](https://github.com/IvanYarlichenco/gameIgra/files/6420773/Usecase.UserStory.docx)
