### ISSUE TITLE
Создать черновики возможных тестов

### ISSUE THREAD

**Issue by Egorrrrr** [IvanYarlichenco/gameIgra#13]
Закинул файл псевдо-тестов чего то

**Comment by IvanYarlichenco** [comment]
[
[Что в принципе может быть не то.txt](https://github.com/IvanYarlichenco/gameIgra/files/6692839/default.txt)
](url)

**Comment by IvanYarlichenco** [comment]
Закинул файл псевдо-тестов чего то

**Comment by IvanYarlichenco** [comment]
Черновик тестов  
Страница логина:
	Тестирование полей
1) Вписывать данные в виде цифр букв спец. Символов
2) Забить правильные данные в разном регистре 
3)  Вводить правильные и неправильные данные
4) Проверить длину полей на количество символов
	Тестирование кнопки Sign in
1)	Нажатие с пустым полем
2)	Нажатие с правильно введенными данными
3)	Нажатие с неправильно введенными данными
4)	Таб назад после нажатия, повторное нажатие
5)	Нажатие с правильно введенными данными в разном регистре

Главная страница

Тест главной страницы
1)	Нажать на якорь главной страницы «trees platform»
2)	Кнопка уведомлений нажать, посмотреть работу, в будущем проверить кликабельность (если есть) уведомлений 
3)	Иконка с аватаркой проверить нажатие, куда ведет, правильность работы
4)	Проверить адаптивность элемента к разному разрешению окна 

Тест бокового меню
1)	Проверить кликабельность каждого компонента
2)	Проверить кликабельность (если есть) аватара в боковом меню 
3)	Проверить адаптивность элемента к разному разрешению окна 
На мобильных устройствах боковое меню будет «выплывать» и «заплывать», проверить на работоспособность в разных условиях:
1.1)	Если развернуть меню и свернуть/развернуть приложение
1.2)	Если развернуть меню и перейти на другой компонент
1.3)	Если развернуть меню, изменить разрешение и свернуть меню
1.4)	Проверить развернутое меню на адаптивность к разным разрешениям окна
Тест элемента «главная»
1)	На главной странице должны содержаться разные ссылки на другие компоненты или на информацию о сайте, проверить кликабельность, работоспособность и правильность отображенной информации (туда ли ведет ссылка, куда надо)
2)	Дальнейшие тестирования невозможны(нет контента)
Тест элемента «задания»
1 Проверить кликабельность компонента
2) Проверить содержащиеся задания, на каждую группу студентов (сами задания должны соответствовать группе/человеку)
3) Задания должны содержать в себе не только сами задания, но и элемент их оценивания, проверить работоспособность проставления оценки(оценено/не оценено + оценка(при наличии)
4) Дальнейшие тестирования невозможны(нет контента)

 Тест элемента «игры»
1) Проверить кликабельность компонента 
2) Пройти все будущие игры, оценить работоспособность, правильность исполнения задуманного «геймплея». 
3)	 Дальнейшие тестирования невозможны(нет контента)

Тест элемента «лекции»
1) Проверить кликабельность
2) Проверить кликабельность и содержание внутреннего компонента – сами лекции.
3) Проверить адаптивность компонентов к разному разрешению окна
4) Дальнейшие тестирования невозможны(нет контента)

Тест компонента «статистика»
1)	Проверить кликабельность
2)	Проверить соответствие заявленной статистики – действительности (преподаватели будут вести личный учет по состоянию предмета (сдан/не сдан долго, о наличии автомата за экзамен и т.д) данные должны совпадать
3)	Проверить адаптивность компонентов к разному разрешению окна
4)	Дальнейшие тестирования невозможны(нет контента)
