### ISSUE TITLE
Разбить приложение на компоненты 

### ISSUE THREAD

**Issue by Egorrrrr** [IvanYarlichenco/gameIgra#17]

**Comment by XeniaWorontsova** [comment]
Я так понимаю, этот таск сделан в https://github.com/IvanYarlichenco/gameIgra/pull/20. Здесь бы тоже упомянуть об этом и перевесить на старшего разработчика.

**Comment by MalyshevKirill** [comment]
> Я так понимаю, этот таск сделан в #20. Здесь бы тоже упомянуть об этом и перевесить на ревьювера.

Завтра учтём

**Comment by XeniaWorontsova** [comment]
Не перевесили на ревьювера, поэтому он может забыть при одобрении запроса закрыть этот таск.
