### ISSUE TITLE
Дизайн страницы логина 

### ISSUE THREAD

**Issue by Egorrrrr** [IvanYarlichenco/gameIgra#19]

**Comment by XeniaWorontsova** [comment]
Не приложили результат и закрыли

**Comment by XeniaWorontsova** [comment]
Всегда должен быть какой-то результат

**Comment by XeniaWorontsova** [comment]
Я не вижу, чтобы что-то было готово)

**Comment by Egorrrrr** [comment]
да щаас

**Comment by Egorrrrr** [comment]
![image](https://user-images.githubusercontent.com/61844509/122875946-94eda480-d33d-11eb-88a9-84a2e32140ff.png)

**Comment by XeniaWorontsova** [comment]
Хорошо, но все-таки порядок надо поменять) Сначала результат и только потом Done и Close. И тогда я не буду вас раздражать)

**Comment by Egorrrrr** [comment]
Окей. Просто с скриншотом задержали)
