### ISSUE TITLE
Разработать концепт приложения

### ISSUE THREAD

**Issue by IvanYarlichenco** [IvanYarlichenco/gameIgra#2]
https://drive.google.com/file/d/1hemhfLoWAU-7IdMtsVwFUFLeOM9GyM8H/view?usp=sharing

**Comment by XeniaWorontsova** [comment]
На доске карточка находится в Done, можно считать, что работа по ней завершена? Если да, то правильно бы было оставить здесь ссылку на док, где описывается концепт или просто написать комментарий по итогу.

**Comment by Egorrrrr** [comment]
на доработку
