### ISSUE TITLE
Верстка компонента бокового меню для приложения

### ISSUE THREAD

**Issue by Egorrrrr** [IvanYarlichenco/gameIgra#22]
![image](https://user-images.githubusercontent.com/61844509/122861581-50a3d980-d328-11eb-820d-5ac63fff6d08.png)

**Comment by MalyshevKirill** [comment]
![image](https://user-images.githubusercontent.com/63231735/122893528-16016780-d34f-11eb-8cb2-2f2cb06291cb.png)

**Comment by IvanYarlichenco** [comment]
Бекграунд на левом боковом  меню при очень маленьком разрешении окна(проблема незначительна)

**Comment by XeniaWorontsova** [comment]
@Egorrrrr в случае когда на таске остаются висеть только незначительные проблемы, ты можешь принять решение, что это неважно, не требует починки и так и написав, закрыть таск

**Comment by Egorrrrr** [comment]
проблема требует починки

**Comment by IvanYarlichenco** [comment]
Проблема устранена
