### ISSUE TITLE
Верстка компонента главной страницы 

### ISSUE THREAD

**Issue by Egorrrrr** [IvanYarlichenco/gameIgra#23]
![image](https://user-images.githubusercontent.com/61844509/122861706-8e086700-d328-11eb-8794-4b37ce2f8d71.png)

**Comment by IvanYarlichenco** [comment]
Тестирую Главную страницу блок "Добро пожаловать на учебную платформу "Trees"
Шаг 1 : Нажимаю на кнопку подробнее

Результаты : ожидаю - подробную информацию
получено : ничего(контент пока не добавлен )
Тестирую адаптивность окна
Шаг 1 - изменяю размеры окна
Ожидаю : верстка адаптируется под разные размеры окна
Результат Верстка адаптирована, проблем не выявлено
