### ISSUE TITLE
Написать процедуру логина, наладить обслуживание клиентов

### ISSUE THREAD

**Issue by Egorrrrr** [IvanYarlichenco/gameIgra#24]
Стори 1:
Как:
	Студент и преподаватель
Я хочу:
	Иметь возможность входить в систему 
Чтобы:
	Получить доступ к соответствующему функционалу

**Comment by IvanYarlichenco** [comment]
Тестирую страницу логина, + запуск клиента.
Было : редирект на пустой бланк.
Ожидается : Редирект на любую не пустую страницу с контентом
Результат : Редиррект на бланк логина
клиент запускается в chrome без ошибок
Тестирую клиент логина:
Ожидается: Ввожу логин и пароль, нажимаю sign in на базу отсылается логин и пароль , получаем его и попадаем на страницу
Результат : Вводим данные ЛП , данные отсылаются, Присылается пустой ответ без данных
 
Ввожу данные из БД в ЛП
Ожидаю : Подтверждение входа по существующим в БД логину и паролю
Результат : Пустой ответ от БД данных нет

**Comment by XeniaWorontsova** [comment]
@IvanYarlichenco Почти все хорошо, но нужно разделить шаги и результат. Т.е. не
![image](https://user-images.githubusercontent.com/33964762/123067728-e8352500-d419-11eb-84ac-a1fa29cd2824.png)
а:
Тестирую клиент логина:
Шаги: 
  1. Ввожу логин и пароль, 
  2. нажимаю sign in
Ожидается:  на базу отсылается логин и пароль , попадаем на страницу
Результат : Присылается пустой ответ без данных
