### ISSUE TITLE
Определиться с выбором технологий

### ISSUE THREAD

**Issue by IvanYarlichenco** [IvanYarlichenco/gameIgra#3]
1. ReactJs - для веб-приложения
2. ReactNative - для приложений на остальные устройства
3. Visual Studio Code - редактор
4. GitHub - система контроля версий и проектная доска

**Comment by XeniaWorontsova** [comment]
Нужно будет еще добавить обоснование технологий.

**Comment by XeniaWorontsova** [comment]
Это не совсем обоснование. Например, пункт 1 - "ReactJs - для веб-приложения" - возникает вопрос: а почему ReactJS? Больше нет библиотек?. К 3 и 4-му пунктам такого обоснования не надо, но вот 1 и 2 требуют дополнения. Так же не подойдет вариант с "мы знаем только это" ) Обоснование предполагает какое-то сравнение библиотек

**Comment by XeniaWorontsova** [comment]
И GitHub нельзя назвать системой контроля версий. Git - система контроля версий, а вот GitHub - нет

**Comment by Timanchik** [comment]
Преимущества ReactJS:
1) Легок в изучении. React гораздо легче учится ввиду простоты его синтаксиса. Инженеры просто должны вспомнить свои навыки написания HTML и всё на этом. Нет нужды в глубоком изучении TypeScript, как в случае с Angular.
2) Высокий уровень гибкости и максимальная отзывчивость.
3) Виртуальная DOM (document object model), которая позволяет упорядочивать документы форматов HTML, XHTML или XML в дерево, которое лучше всего подходит веб-браузерам для анализа различных элементов веб-приложения.
4) Связывание данных от больших к меньшим. Это означает такой поток данных, при котором дочерние элементы не могут влиять на родительские данные.
5) 100%-ая JavaScript-библиотека с открытым исходным кодом, которая получает множество ежедневных обновлений и улучшений в соответствии с отзывами разработчиков по всему миру.
6) Невероятно легкий вес, так как данные, которые выполняются на стороне пользователя, могут легко быть представлены на стороне сервера в то же самое время.

**Comment by XeniaWorontsova** [comment]
Не Done - я вспомнила, что Егор обещал отредактировать обоснования для 3 и 4 пунктов
