### ISSUE TITLE
Сверстать страницу с лекциями(компонент для карточек/кнопок с лекциями)

### ISSUE THREAD

**Issue by Egorrrrr** [IvanYarlichenco/gameIgra#33]
Сделать страницу с лекциями(компонент для карточек/кнопок с лекциями)
![image](https://user-images.githubusercontent.com/61844509/122916377-7bf8e980-d365-11eb-9faf-35d9e9e30333.png)

**Comment by MalyshevKirill** [comment]
![image](https://user-images.githubusercontent.com/63231735/123013981-ee051900-d3cd-11eb-97d9-0b0b3b9514e7.png)
