### ISSUE TITLE
Дизайн интерфейса главного администратора, включающий в себя функционал добавления и удаления преподавателя

### ISSUE THREAD

**Issue by Egorrrrr** [IvanYarlichenco/gameIgra#38]

**Comment by Timanchik** [comment]
![Добавление препод](https://user-images.githubusercontent.com/61830429/123118724-8d1c2600-d44b-11eb-8a7a-4fbf17dda688.png)
![Интерфейс добавленияё](https://user-images.githubusercontent.com/61830429/123118738-8f7e8000-d44b-11eb-9088-e059e824ab9f.png)
![Монтажная область 1](https://user-images.githubusercontent.com/61830429/123118744-90171680-d44b-11eb-99ae-09a972bbf53c.png)
![Препод](https://user-images.githubusercontent.com/61830429/123118747-90afad00-d44b-11eb-89f5-c9fc16132c07.png)
