### ISSUE TITLE
Дизайн редактора тестов

### ISSUE THREAD

**Issue by Egorrrrr** [IvanYarlichenco/gameIgra#39]
Стори 6:
Как:
	Преподаватель
Я хочу:
	Иметь возможность редактировать или добавлять тестовые задания
Чтобы:
	Привносить разнообразие и избежать списывания

**Comment by Timanchik** [comment]
![Создание теста](https://user-images.githubusercontent.com/61830429/123210806-33f3d700-d4cb-11eb-9f0c-6f63bf13c66b.png)
![Тест](https://user-images.githubusercontent.com/61830429/123210811-36563100-d4cb-11eb-8334-c19427faf7ad.png)
![Тесты](https://user-images.githubusercontent.com/61830429/123210814-37875e00-d4cb-11eb-9d7a-ab0514f3d2b2.png)
1) При создании нового задан поваляется всплывающее меню, которое предложит создать задание одного из трех представленных типов: Задание с выбором одного ответа, задание с выбором нескольких ответов и задание с развёрнутым ответом.
2) После удачного создания, тест появляется на вкладке "Задания"
