### ISSUE TITLE
Дизайн меню загрузки лекционного материла

### ISSUE THREAD

**Issue by Egorrrrr** [IvanYarlichenco/gameIgra#40]
Стори 8:
Как:
	Преподаватель
Я хочу:
	Добавлять лекционный  материал
Чтобы:
	Студенты могли ознакомиться с материалом

**Comment by Timanchik** [comment]
![Лекции_препод](https://user-images.githubusercontent.com/61830429/123206991-54b92e00-d4c5-11eb-8c05-e307e6390920.png)
![СозданиеЛекций](https://user-images.githubusercontent.com/61830429/123206994-57b41e80-d4c5-11eb-957e-f0d3b4e2baad.png)
