### ISSUE TITLE
Написание кода для редактора тестов

### ISSUE THREAD

**Issue by Egorrrrr** [IvanYarlichenco/gameIgra#44]
Стори 6:
Как:
	Преподаватель
Я хочу:
	Иметь возможность редактировать или добавлять тестовые задания
Чтобы:
	Привносить разнообразие и избежать списывания

**Comment by IvanYarlichenco** [comment]
Приступаю к тестированию редактора тестов
Шаг 1 нажимаю на "+" в правом нижнем углу экрана
Ожидания: открывается редактор тестов
Результат: ожидания оправдались 
Шаг 2. Нажму кнопку "добавить"
Ожидание : добавляется пустой тест без данных
Результат : ожидания оправдались
Шаг 3. Нажму кнопку "отмена" 
Ожидания: окно редактора тестов закроется
Результат: ожидания оправдались
Тестирую поля редактора тестов
Шаг 1 - нажимаю на поле название
Ожидания: можно поменять название
Результат : ожидания оправдались
Шаг 2 - тестирую различные комбинации клавиш на поле "название"
Ожидания:никаких проблем с добавление любого названия
Результат: ожидания оправдались 
Продолжаю тестировать редактор тестов
Шаг 1. Нажму на "+" под полем "название"
Ожидания - добавляется пустой вопрос без всего
Результат - ожидания оправдались 
Шаг 2. Пробую различные вариации заполнения поля теста:
1)добавляю пустой тест
2)добавляю тест с одним правильным вопросом
3)добавляю тест с одним правильным и одним неправильным вопросом
4)добавляю тест с множеством пустых правильным полей
5)добавляю тест с множеством пустых неправильных полей
6)Добавляю тесты с названием и множеством ответов на вопросы(предыдущие тестирования основывались на полях с одним ответом на вопрос)
7)Добавляю множество вопросов с указанными выше способами тестирования
8)пробую удалить вопрос
9)пробую удалить ответ
10)Подтверждаю ответ, потом отменяю его
11)Создаю множество полей без нажатия на кнопку "добавить"
12)Нажимаю отмена при наличии вопросов 
13)Добавляю несколько тестов с указанными выше способами тестирования
Результаты тестирования: данные работают корректно, багов и ошибок не обнаружено
Вопросы добавляются коррекнто пустые поля обрабатываются как поле без ответа(с названием "ответ"
Тесты свободно создаются и удаляются, работает кнопка "отмена" кнопка "добавить"
