### ISSUE TITLE
Поставить иконку с логотипом(которая на вкладке)

### ISSUE THREAD

**Issue by Egorrrrr** [IvanYarlichenco/gameIgra#46]

**Comment by Egorrrrr** [comment]
screenshot, please

**Comment by MalyshevKirill** [comment]
![image](https://user-images.githubusercontent.com/63231735/123213833-2a6c6e00-d4cf-11eb-9e58-767cf77ef12d.png)

**Comment by IvanYarlichenco** [comment]
Тестировать нечего, иконка как иконка, работает без ошибок
