### ISSUE TITLE
Баг логина с передачей данных

### ISSUE THREAD

**Issue by Egorrrrr** [IvanYarlichenco/gameIgra#51]

**Comment by IvanYarlichenco** [comment]
Тестирую страницу логина, + запуск клиента. Повторно
Старый результат : При отправке данных в БД приходит пустой ответ без данных авторизация невозможно, всегда выдает ошибкую
Проверяю заново 
Шаги:
1)Заполняю логин и пароль
2) нажимаю sign in 
Ожидается : старая ошибка 
Результат: Дается ответ с данными, удается получить доступ к авторизированной странице
Вывод: Ошибки исправлены
