### ISSUE TITLE
Разработать БД

### ISSUE THREAD

**Issue by IvanYarlichenco** [IvanYarlichenco/gameIgra#6]
https://drive.google.com/file/d/1InZWIqXWyih-uTEwbecbNrW_N4CN0iQg/view?usp=sharing

**Comment by XeniaWorontsova** [comment]
Вы сейчас у Нины Олеговны строите такие диаграммы? По-моему, это не соответствует нотации. Не отображены виды связей между таблицами, не стоит явное обозначение всех типов ключей... Если это какая-то другая нотация, то расскажите, что это за нотация...

**Comment by XeniaWorontsova** [comment]
Вопросы по содержанию: 
1) Почему в таблице Задание у нас есть поля Предмет, Тема и Курс? У нас же только на одну тему приложение делается, соответственно и на один предмет
2) То же самое с таблицей Лекционный материал
3) Что значит поле "Статус" в таблице Лекционный материал?
4) И, наверное, лучше переименовать таблицу Администратор все-таки назад в "Преподаватель", потому что тут немного будет путать сознание людей, так как в голову сразу идет администратор баз данных. Вы можете просто сказать, что у преподавателя расширенные возможности по сравнению со студентом. И тогда таблицу "Пользователь" так же нужно переименовать в "Студент", потому что а чем вам "Преподаватель" не пользователь?
