### ISSUE TITLE
Верстка компонента списка пользователей(учителей/студентов) для администраторов

### ISSUE THREAD

**Issue by MalyshevKirill** [IvanYarlichenco/gameIgra#62]

**Comment by MalyshevKirill** [comment]
![image](https://user-images.githubusercontent.com/63231735/123255224-446e7680-d4f8-11eb-9cf3-93dace0c22bc.png)

**Comment by IvanYarlichenco** [comment]
Верстка адаптированная, проблем не обнаружено
