### ISSUE TITLE
Верстка компонента добавления новых пользователей(учителей/студентов) для администраторов

### ISSUE THREAD

**Issue by MalyshevKirill** [IvanYarlichenco/gameIgra#64]

**Comment by MalyshevKirill** [comment]
![image](https://user-images.githubusercontent.com/63231735/123316970-27589880-d536-11eb-87f6-859d7f5cebd3.png)

**Comment by IvanYarlichenco** [comment]
Верстка адаптивная, проблем не выявлено(до пула)

**Comment by IvanYarlichenco** [comment]
Отсмотрено, верстка адаптивная, проблемы не обнаружены
