### ISSUE TITLE
Сделать Презентацию 29.04

### ISSUE THREAD

**Issue by IvanYarlichenco** [IvanYarlichenco/gameIgra#7]

**Comment by XeniaWorontsova** [comment]
Done? :) Но где же ссылка? (можно оставить ссылку, но предоставлять доступ только по запросу, если не хочется, чтобы кто-то лишний увидел)

**Comment by Egorrrrr** [comment]
https://drive.google.com/file/d/1rrkmoG1IBFT9ek2MokDPagJA0JiMjj06/view?usp=sharing
