### ISSUE TITLE
Дизайн меню статистики и карточек со статистикой

### ISSUE THREAD

**Issue by Egorrrrr** [IvanYarlichenco/gameIgra#71]

**Comment by Timanchik** [comment]
![Статистика игры](https://user-images.githubusercontent.com/61830429/123229731-3e1fd080-d4df-11eb-847f-fe5cf0f2b303.png)
![Статистика](https://user-images.githubusercontent.com/61830429/123229737-40822a80-d4df-11eb-8ac7-de6c584faf13.png)
